services:

  keelson-processor-ais:
    # build: .
    image: ghcr.io/rise-maritime/keelson-processor-ais:latest
    container_name: keelson-processor-ais
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 1830:1830/udp 
    # command: "--log-level 10 -r rise -e masslab --publish udp_sjv --subscribe sjofartsverket"
    command: "--log-level 10 --publish udp_sjv --subscribe sjofartsverket"
    
