services:

  keelson-processor-ais:
    # build: .
    image: ghcr.io/rise-maritime/keelson-processor-ais:latest
    container_name: keelson-processor-ais
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 10110:10110/udp 
    command: "--log-level 10 -r rise -e erik --subscribe sjofartsverket --publish sjv_nmea_udp --udp-port 10110"
    
